jobs:
  - job: MINGW
    timeoutInMinutes: 360
    pool:
      vmImage: vs2017-win2016
    strategy:
      maxParallel: 5
      matrix:
        i686:
          RTOOLS_ARCH: x86_64
          MINGW_INSTALLS: mingw32
        x86_64:
          RTOOLS_ARCH: x86_64
          MINGW_INSTALLS: mingw64
    steps:
      - powershell: |
          (New-Object System.Net.WebClient).DownloadFile('http://repo.msys2.org/msys/x86_64/pacman-5.2.1-6-x86_64.pkg.tar.xz', 'pacman-5.2.1-6-x86_64.pkg.tar.xz')
          C:\msys64\usr\bin\pacman -U --noconfirm pacman-5.2.1-6-x86_64.pkg.tar.xz
          C:\msys64\usr\bin\pacman -Syu --noconfirm
        displayName: Installing msys64 build environment
      - script: |
          rmdir /s /Q "C:\Program Files\Boost"
          C:\msys64\usr\bin\pacman --noconfirm --needed -S git
          C:\msys64\usr\bin\bash --login -c "$(cygpath ${SYSTEM_DEFAULTWORKINGDIRECTORY})/ci-build.sh"
        displayName: Building Packages
        env:
          BUILD_URL: dummy
          DEPLOY_PROVIDER: bintray
          BINTRAY_TARGET: rtools
          BINTRAY_REPOSITORY: $(MINGW_INSTALLS)
          PACMAN_REPOSITORY: $(MINGW_INSTALLS)
      - task: PublishPipelineArtifact@1
        displayName: Storing artifacts
        inputs:
          targetPath: artifacts
          artifactName: $(MINGW_INSTALLS)-repo.zip
